sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
  - "7"
  - "6"

matrix:
  include:
    - os: linux
      node_js: "stable"
      env: JOB_PART=lint
    - os: linux
      node_js: "stable"
      env: JOB_PART=integration
    - os: linux
      node_js: "8"
      env: JOB_PART=integration
    - os: linux
      node_js: "7"
      env: JOB_PART=integration
    - os: linux
      node_js: "6"
      env: JOB_PART=integration

before_install:
  - npm i -g npm@latest
  - npm ci
  - npm install -g codecov
  - npm install -g eslint

jobs:
  include:
    - stage: commit lint
      script: commitlint-travis
    - stage: NPM release
      if: branch = master
      node_js: "lts/*"
      script: npm run travis-deploy-once "npm run semantic-release"