language: node_js

matrix:
  include:
    - os: linux
      node_js: "stable"
      env: JOB_PART=lint
    - os: linux
      node_js: "stable"
      env: JOB_PART=integration
    - os: linux
      node_js: "8"
      env: JOB_PART=integration
    - os: linux
      node_js: "7"
      env: JOB_PART=integration
    - os: linux
      node_js: "6"
      env: JOB_PART=integration

sudo: false

notifications:
  email: false

install:
  - yarn add global codecov
  - yarn add global eslint
  - yarn add global babel-eslint
  - yarn add global eslint-plugin-node
  - yarn add global eslint-plugin-flowtype@latest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run travis:$JOB_PART
