sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
  - "7"
  - "6"

matrix:
  include:
    - os: linux
      node_js: "stable"
      env: JOB_PART=lint
    - os: linux
      node_js: "stable"
      env: JOB_PART=integration
    - os: linux
      node_js: "8"
      env: JOB_PART=integration
    - os: linux
      node_js: "7"
      env: JOB_PART=integration
    - os: linux
      node_js: "6"
      env: JOB_PART=integration

before_install:
  - npm i -g npm@latest
  - npm ci
  - npm install -g codecov
  - npm install -g eslint

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: commit lint
      script: commitlint-travis
    - stage: NPM release
      if: branch = master
      node_js: "8"
      script: echo "Deploying new webpack-cli version to npm ..."
      deploy:
        script: npx semantic-release
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release