language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "stable"

sudo: false

notifications:
  email: false

before_install:
- yarn global add eslint

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bash <(curl -s https://codecov.io/bash)

script:
  - yarn prepare
  - yarn lint
  - yarn test
