name: webpack-cli

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test description'

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
        webpack-version: [latest]

    steps:
      - uses: actions/checkout@v2

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Bootstrap
        run: yarn lerna bootstrap

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

  build:
    name: Tests and Coverage - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}, DevServer ${{ matrix.dev-server-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x, 14.x]
        webpack-version: [4, latest]
        dev-server-version: [latest, next]
        exclude:
          - node-version: 10.x
            dev-server-version: next

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore lerna cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: c-${{ runner.os }}-${{ matrix.webpack-version }}-yarn-${{ hashFiles('**/yarn.lock', './yarn.lock') }}
          restore-keys: |
            c-${{ runner.os }}-${{ matrix.webpack-version }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Install webpack ${{ matrix.webpack-version }}
        run: yarn add -W webpack@${{ matrix.webpack-version }}

      - name: Install webpack-dev-server ${{ matrix.webpack-version }}
        run: yarn add -W webpack-dev-server@${{ matrix.dev-server-version }}

      - name: Prepare environment for tests
        run: yarn build:ci

      - name: Run smoketests
        run: yarn test:smoketests

      - name: Run tests and generate coverage
        run: |
          yarn prepsuite
          yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install

      - name: conventional-changelog-lint-config-cz
        # $GITHUB_WORKSPACE is the path to your repository
        run: echo "NODE_PATH=$GITHUB_WORKSPACE/node_modules" >> $GITHUB_ENV

      - uses: wagoid/commitlint-github-action@v2
