name: webpack-cli

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: read

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    runs-on: ${{ matrix.os }}

    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
        webpack-version: [latest]

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  build:
    name: Tests and Coverage - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}, DevServer ${{ matrix.dev-server-version }} (${{ matrix.shard }})

    runs-on: ${{ matrix.os }}

    concurrency:
      group: build-${{ matrix.os }}-v${{ matrix.node-version }}-${{ matrix.webpack-version }}-${{ matrix.dev-server-version }}-${{ matrix.shard }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [24.x]
        shard: ["3/4"]
        webpack-version: [latest]
        dev-server-version: [latest]

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 #4.2.0
        with:
          version: 9

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Prepare environment for tests
        run: npm run build:ci

      - name: Run tests and generate coverage
        run: npm run test:coverage -- --ci --shard=${{ matrix.shard }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  smoketests:
    name: Smoketests - ${{ matrix.os }} - Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    concurrency:
      group: smoketests-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prepare environment for tests
        run: npm run build:ci

      - name: Run smoketests
        run: npm run test:smoketests

  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    concurrency:
      group: commitlint-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
