name: webpack-cli

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next
  workflow_dispatch:
    inputs:
      tags:
        description: "Test description"

permissions:
  contents: read

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    runs-on: ${{ matrix.os }}

    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
        webpack-version: [latest]

    steps:
      - uses: actions/checkout@v3

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Bootstrap
        run: yarn lerna bootstrap

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

  build:
    name: Tests and Coverage - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}, DevServer ${{ matrix.dev-server-version }} (${{ matrix.shard }})

    runs-on: ${{ matrix.os }}

    concurrency:
      group: build-${{ matrix.os }}-v${{ matrix.node-version }}-${{ matrix.webpack-version }}-${{ matrix.dev-server-version }}-${{ matrix.shard }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [14.x, 16.x, 18.x, 19.x]
        shard: ["1/4", "2/4", "3/4", "4/4"]
        webpack-version: [latest]
        dev-server-version: [latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines

      - name: Prepare environment for tests
        run: yarn build:ci

      - name: Run tests and generate coverage
        run: yarn jest serve-basic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  smoketests:
    name: Smoketests - ${{ matrix.os }} - Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    concurrency:
      group: smoketests-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines

      - name: Prepare environment for tests
        run: yarn build:ci

      - name: Run smoketests
        run: yarn test:smoketests

  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    concurrency:
      group: commitlint-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - run: yarn --frozen-lockfile

      - uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
