name: webpack-cli

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: read

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    runs-on: ${{ matrix.os }}

    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
        webpack-version: [latest]

    steps:
      - uses: actions/checkout@v4

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --include-workspace-root

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  build:
    name: Tests and Coverage - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}, DevServer ${{ matrix.dev-server-version }} (${{ matrix.shard }})

    runs-on: ${{ matrix.os }}

    concurrency:
      group: build-${{ matrix.os }}-v${{ matrix.node-version }}-${{ matrix.webpack-version }}-${{ matrix.dev-server-version }}-${{ matrix.shard }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x, 24.x]
        shard: ["1/4", "2/4", "3/4", "4/4"]
        webpack-version: [latest]
        dev-server-version: [latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: npm ci --ignore-engines --ignore-scripts --include-workspace-root

      - name: Prepare environment for tests
        run: npm run build:ci

      - name: Run tests and generate coverage
        run: npm run test:coverage --ci --shard=${{ matrix.shard }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  smoketests:
    name: Smoketests - ${{ matrix.os }} - Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    concurrency:
      group: smoketests-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --ignore-engines --include-workspace-root

      - name: Prepare environment for tests
        run: npm run build:ci

      - name: Run smoketests
        run: npm run test:smoketests

  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    concurrency:
      group: commitlint-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci --include-workspace-root

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
