name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: read

jobs:
  lint:
    name: Lint

    runs-on: ${{ matrix.os }}

    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
        webpack-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  test:
    name: Test - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}, DevServer ${{ matrix.dev-server-version }}

    runs-on: ${{ matrix.os }}

    concurrency:
      group: test-${{ matrix.os }}-v${{ matrix.node-version }}-${{ matrix.webpack-version }}-${{ matrix.dev-server-version }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x, 24.x]
        webpack-version: [latest]
        dev-server-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Add workspace to Defender exclusions
        if: matrix.os == 'windows-latest'
        run: |
          Add-MpPreference -ExclusionPath "${{ github.workspace }}"

          Add-MpPreference -ExclusionProcess "node.exe"

          $npmCache = (npm config get cache)
          Add-MpPreference -ExclusionPath $npmCache

          Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell

      - name: Using Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 #4.2.0
        with:
          version: 10

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Prepare environment for tests
        run: npm run build

      - name: Run tests and generate coverage
        run: npm run test:coverage -- --ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  smoketests:
    name: Smoketests

    runs-on: ${{ matrix.os }}

    concurrency:
      group: smoketests-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Using Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prepare environment for tests
        run: npm run build

      - name: Run smoketests
        run: npm run test:smoketests
