name: webpack-cli

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next
  workflow_dispatch:
    inputs:
      tags:
        description: "Test description"

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Node v${{ matrix.node-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
        webpack-version: [latest]

    steps:
      - uses: actions/checkout@v3

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Bootstrap
        run: yarn install

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

  build:
    name: Tests and Coverage - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}, DevServer ${{ matrix.dev-server-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]
        webpack-version: [latest]
        dev-server-version: [latest]
        include:
          - node-version: 16.x
            os: ubuntu-latest
            dev-server-version: version-3
            webpack-version: latest
          - node-version: 16.x
            os: ubuntu-latest
            dev-server-version: latest
            webpack-version: webpack-4
        exclude:
          - node-version: 10.x
            dev-server-version: latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines

      - name: Install webpack ${{ matrix.webpack-version }}
        if: matrix.webpack-version == '4'
        run: yarn add -W webpack@${{ matrix.webpack-version }} --ignore-engines

      - name: Install webpack-dev-server ${{ matrix.dev-server-version }}
        if: matrix.dev-server-version == 'version-3'
        run: yarn add -W webpack-dev-server@${{ matrix.dev-server-version }} --ignore-engines

      - name: Prepare environment for tests
        run: yarn build:ci

      - name: Run smoketests
        run: yarn test:smoketests

      - name: Run tests and generate coverage
        run: |
          yarn prepsuite
          yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - run: yarn --frozen-lockfile

      - name: conventional-changelog-lint-config-cz
        # $GITHUB_WORKSPACE is the path to your repository
        run: echo "NODE_PATH=$GITHUB_WORKSPACE/node_modules" >> $GITHUB_ENV

      - uses: wagoid/commitlint-github-action@v4
