name: webpack-cli

on:
  push:
    branches:
    - master
    - next
  pull_request:
    branches:
    - master
    - next

jobs:
  lint:
    name: Lint - ${{ matrix.os }} - Node v${{ matrix.node }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [12]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Using Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn
          yarn bootstrap

      - name: Lint
        run: yarn lint

  build:
    name: Tests - ${{ matrix.os }} - Node v${{ matrix.node-version }}, Webpack ${{ matrix.webpack-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x, 13.x]
        webpack-version: [next, latest]

    steps:
    - uses: actions/checkout@v2

    - name: Using Node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        yarn
        yarn bootstrap

    - name: Run tests for webpack version ${{ matrix.webpack-version }}
      run: |
        yarn add -W webpack@${{ matrix.webpack-version }}
        yarn build
        yarn prepsuite
        node_modules/.bin/jest test/node
#        yarn test:ci
      env:
        CI: true

#    - name: Smoke Tests
#      run: yarn smoketest
#      env:
#        CI: true
